# 配置文件

DAILY_TIME: "08:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-01-07" # 纪念日
CITY: "德阳"

jiloveday:
  - "01-07"

APP_ID wx587cb2647b6f167c: "微信公众平台的 APP ID"
APP_ID 307826b08982ffc08fd34eb030a033f7: "微信公众平台的 APP SECRET"

USER_ID:fBSBGFaFF0cpDs0hGxGbIfH4qOCEcXtcvPZbALFzsfg 
  - "微信公众平台的 USER ID"
  - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "微信公众平台的 TEMPLATE ID"
